#!/usr/bin/env bash
# Generated by install.sh — the `relava` dispatcher command. Deliberately
# thin: it only knows how to find the real tool source (SRC_DIR, filled in
# at install time below) and forward to it. If relava's CLI is ever
# reimplemented as a compiled binary instead of bash, only this file (and
# its Windows .cmd sibling, also written by install.sh) needs to change —
# everything that already types `relava init`/`relava sync` on the command
# line keeps working unmodified.
set -uo pipefail

SRC_DIR="__SRC_DIR__"

case "${1:-}" in
    init)
        shift
        if [ "$#" -ge 1 ]; then
            # An explicit repo URL was given — skip init.sh's interactive
            # auto-create-or-decline prompt entirely and join that repo
            # directly. bootstrap.sh already supports this via its own
            # positional remote-url argument.
            exec bash "$SRC_DIR/sync/bootstrap.sh" "$1"
        else
            exec bash "$SRC_DIR/sync/init.sh"
        fi
        ;;
    sync)
        shift
        exec bash "$SRC_DIR/sync/sync.sh" "$@"
        ;;
    *)
        echo "usage: relava <init|sync> [args]" >&2
        echo "  relava init [<existing-repo-url>]   first-run setup, or join an existing kb repo" >&2
        echo "  relava sync [pull|push|full]        manually run a sync (normally automatic via hooks)" >&2
        exit 1
        ;;
esac
